# Configuration file for FL100 MAG reconstruction pipeline
# Edit this file with your system-specific paths and settings

project_name: "lemaylab_MAG_reconstruction"  
sample_sheet: "sample_sheet.txt"

# Input/Output directories
input_reads: "fastq_files"
input_contigs: "contigs"
sample_sheet: "sample_sheet.txt"

# Path to GTDB-Tk database
gtdbtk_data: "/path/to/release214" # Change path 
  
# Conda environment paths, best to keep this in path/to/project/root
conda_envs:
  bwa: "envs/BWA.yaml"
  checkm: "envs/CHECKM.yaml"
  coverm: "envs/COVERM.yaml"
  gtdbtk: "envs/GTDBTK.yaml"
  metabat2: "envs/METABAT2.yaml"
  samtools: "envs/SAMTOOLS.yaml"
  
# Resource allocation (memory in GB, runtime in minutes)
# Resource configurations for each step
resources:
  bwa:
    threads: 8
    mem_mb: 8000
    runtime: 360     # minutes

  samtools:
    threads: 4
    mem_mb: 4000
    runtime: 120

  metabat2:
    threads: 8
    mem_mb: 16000
    runtime: 480

  checkm:
    threads: 8
    mem_mb: 16000
    runtime: 720
    completion_threshold: 50      # minimum % completeness
    contamination_threshold: 10   # maximum % contamination

  gtdbtk:
    threads: 8
    mem_mb: 32000
    runtime: 1440

  coverm:
    threads: 8
    mem_mb: 8000
    runtime: 240
