# Configuration file for FL119 Metagenome Pipeline
# Edit this file with your system-specific paths and settings

# Project settings
project_name: "PROJECT_NAME"  # Change to your project name

# Input/Output directories
input_dir: "fastq_files"
sample_sheet: "sample_sheet.txt"

# Database paths - EDIT THESE FOR YOUR SYSTEM
databases:
  # Path to bowtie2 index for human genome (built with bowtie2-build)
  human_genome: "path/to/human/genome"
  
  # Path to MetaPhlAn database directory
  # metaphlan --install --bowtie2db ~/db/metaphlan_databases
  metaphlan_db: "path/to/MetaPhlan/database/directory"
  
  # MetaPhlAn index name (check for updates at https://github.com/biobakery/MetaPhlAn)
  metaphlan_index: "mpa_vJan25_CHOCOPhlAnSGB_202503"

# Conda environment paths, best to keep this in path/to/project/root
conda_envs:
  fastqc_multiqc: "envs/fastqc_multiqc.yaml"
  bowtie: "envs/bowtie.yaml"
  fastp: "envs/fastp.yaml"
  metaphlan: "envs/metaphlan.yaml"

# Specify version of metaphlan for final outputs
versions:
  metaphlan: "4-2-2"

# Resource allocation (memory in GB, runtime in minutes)
resources:
  fastqc:
    threads: 4
    mem_gb: 16
    runtime_min: 240
  
  bowtie2:
    threads: 8
    mem_gb: 64
    runtime_min: 1440  # 24 hours
  
  fastp_trim:
    threads: 4
    mem_gb: 16
    runtime_min: 360  # 6 hours
  
  fastp_merge:
    threads: 4
    mem_gb: 16
    runtime_min: 360  # 6 hours
  
  metaphlan:
    threads: 4
    mem_gb: 64
    runtime_min: 720  # 12 hours

# Quality filtering parameters for fastp
fastp_params:
  trim:
    min_length: 99
    quality_phred: 30
  merge:
    overlap_len_require: 10
    overlap_diff_percent_limit: 10
